name: PSGallery
on:
  release:
    types: [released]
jobs:
  psgallery_publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        
      - name: Publishing
        run: |
          Publish-Module -Path 'Read-OleDbData' -NuGetApiKey ${{ secrets.PS_GALLERY_KEY }}
        shell: pwsh
